# Generated by Django 5.1.4 on 2025-08-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_plugin_hrm', '0004_remove_leaverequest_approved_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
