# Generated by Django 5.1.4 on 2025-08-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_plugin_hrm', '0006_remove_employee_department_remove_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='pincode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
