# Generated by Django 5.1.4 on 2025-08-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_plugin_hrm', '0007_employee_address_employee_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.TextField(default=''),
        ),
    ]
