# Generated by Django 5.1.4 on 2025-08-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_plugin_hrm', '0008_employee_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
