# Generated by Django 5.1.4 on 2025-08-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_plugin_hrm', '0009_alter_employee_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='is_active',
        ),
    ]
