# Generated by Django 5.1.4 on 2025-08-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_plugin_hrm', '0010_remove_leavetype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
