# Generated by Django 5.1.4 on 2025-08-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_plugin_hrm', '0011_alter_leavetype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
    ]
